phrase:
  access_token: __TOKEN__
  project_id: 1c94699dfcbef0246105e2cca88df5b6
  push:
    sources:
    - file: ./app/i18n/en.json
      params:
        file_format: react_nested_json
        locale_id: en
        update_translations: true
  pull:
    targets:
    - file: app/i18n/es.json
      params:
        file_format: react_nested_json
        locale_id: es
