require("../app/components/currency-text/currency-text.story")
require("../app/components/balance-header/balance-header.story")
require("../app/components/input-payment/input-payment.story")
require("../app/components/price-graph/price-graph.story")
require("../app/components/large-button/large-button.story")
require("../app/components/modal-clipboard/modal-clipboard.story")

require("../app/screens/earns-screen/earns-quiz.story")
require("../app/screens/splash-screen/splash-screen.story")
require("../app/screens/accounts-screen/accounts-screen.story")
require("../app/screens/earns-screen/section-completed.story")
require("../app/screens/earns-map-screen/earns-map-screen.story")
require("../app/screens/transaction-detail-screen/transaction-detail-screen.story")
require("../app/screens/transaction-screen/transaction-screen.story")
require("../app/screens/move-money-screen/move-money-screen.story")
require("../app/screens/phone-auth-screen/phone-auth.story")
require("../app/screens/move-money-screen/receive-bitcoin-screen.story")

