// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import ca from './ca'
import cs from './cs'
import de from './de'
import en from './en'
import es from './es'
import fr_CA from './fr-CA'
import pt_BR from './pt-BR'
import sw from './sw'
import th from './th'
import tr from './tr'

const localeTranslations = {
	ca,
	cs,
	de,
	en,
	es,
	'fr-CA': fr_CA,
	'pt-BR': pt_BR,
	sw,
	th,
	tr,
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
