local_resource(
  name='init-onchain',
  labels = ['dev-setup'],
  cmd='vendor/galoy-quickstart/bin/init-onchain.sh',
  resource_deps = [
    "bitcoind",
    "bria",
  ]
)
local_resource(
  name='init-lightning',
  labels = ['dev-setup'],
  cmd='vendor/galoy-quickstart/bin/init-lightning.sh',
  resource_deps = [
    "lnd1",
    "lnd-outside-1",
  ]
)

docker_compose('vendor/galoy-quickstart/docker-compose.yml')
galoy_services = ["apollo-router", "galoy", "trigger", "redis", "mongodb", "mongodb-migrate", "price", "price-history", "price-history-migrate", "postgres-price-history", "svix", "svix-pg", "stablesats"]
auth_services = ["oathkeeper", "kratos", "kratos-pg", "hydra", "postgresdhydra", "hydra-migrate"]
bitcoin_services = ["bitcoind", "bitcoind-signer", "lnd1", "lnd-outside-1", "bria", "postgres-bria", "fulcrum"]

for service in galoy_services:
    dc_resource(service, labels = ["galoy"])
for service in auth_services:
    dc_resource(service, labels = ["auth"])
for service in bitcoin_services:
    dc_resource(service, labels = ["bitcoin"])

dc_resource('otel-agent', labels = ["otel"])
dc_resource('quickstart-test', labels = ['quickstart'], auto_init=False)
