export const graphqlV2OperationNames: string[] = [
  "captchaCreateChallenge",
  "captchaRequestAuthCode",
  "intraLedgerPaymentSend",
  "lnInvoiceFeeProbe",
  "lnInvoicePaymentSend",
  "lnNoAmountInvoiceFeeProbe",
  "lnNoAmountInvoicePaymentSend",
  "onChainPaymentSend",
  "onChainTxFee",
  "transactionsList",
  "transactionsListForContact",
  "userLogin",
  "userWalletId",
]
