export const graphqlV2OperationNames: string[] = [
  "businessMapMarkers",
  "captchaCreateChallenge",
  "captchaRequestAuthCode",
  "contacts",
  "intraLedgerPaymentSend",
  "lnInvoiceFeeProbe",
  "lnInvoicePaymentSend",
  "lnNoAmountInvoiceFeeProbe",
  "lnNoAmountInvoicePaymentSend",
  "onChainPaymentSend",
  "onChainTxFee",
  "transactionsList",
  "transactionsListForContact",
  "userQuizQuestionUpdateCompleted",
  "userLogin",
  "userDefaultWalletId",
]
