extend type Transaction {
  date: String!
  date_format: String!
  date_nice_print: String!
  isReceive: Boolean!
  text: String!
}

extend type Contact {
  prettyName: String!
}

extend type Query {
  hideBalance: Boolean!
  hiddenBalanceToolTip: Boolean!
  price: String # FIXME test only?
  beta: Boolean!
  colorScheme: String!
  feedbackModalShown: Boolean!
  hasPromptedSetDefaultAccount: Boolean!
  introducingCirclesModalShown: Boolean!
  innerCircleValue: Int!
}

extend type Account {
  usdWallet: UsdWallet
  btcWallet: BTCWallet
  defaultWallet: Wallet
}

extend type ConsumerAccount {
  usdWallet: UsdWallet
  btcWallet: BTCWallet
  defaultWallet: Wallet
}
