
extend type Contact {
  prettyName: String!
}

extend type Query {
  hideBalance: Boolean!
  hiddenBalanceToolTip: Boolean!
  price: String # FIXME test only?
  beta: Boolean!
  colorScheme: String!
  countryCode: String!
  feedbackModalShown: Boolean!
  hasPromptedSetDefaultAccount: Boolean!
  introducingCirclesModalShown: Boolean!
  innerCircleValue: Int!
}

extend type Account {
  usdWallet: UsdWallet
  btcWallet: BTCWallet
}

extend type ConsumerAccount {
  usdWallet: UsdWallet
  btcWallet: BTCWallet
}
