export const WHATSAPP_CONTACT_NUMBER = "+50369835117"
export const GALOY_PAY_DOMAIN = "https://ln.bitcoinbeach.com/"
export const BLOCKCHAIN_EXPLORER_URL = "https://mempool.space/tx/"
export const CONTACT_EMAIL_ADDRESS = "support@bbw.sv"
export const CONTACT_PHONE_NUMBER = "+50372089187"
