source "https://rubygems.org"
ruby '2.7.7'
gem "fastlane"
gem 'cocoapods', '~> 1.11', '>= 1.12.0'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
