source "https://rubygems.org"
ruby '2.7.7'

gem 'fastlane', '2.213.0'
gem 'cocoapods', '~> 1.14', '>= 1.14.3'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
