# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "GaloyApp.xcodeproj")
    match(type: "appstore", readonly: is_ci)
    gym(scheme: "GaloyApp")

    app_store_connect_api_key(
      key_id: ENV["APPSTORE_API_KEYID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_API_KEY"],
      is_key_content_base64: true
    )

    upload_to_testflight(changelog: "No changelog")
 
    # build_app(workspace: "GaloyApp.xcworkspace", scheme: "GaloyApp")
    # upload_to_testflight
  end

  desc "Upload to browserstack for testing"
  lane :browserstack do
    build_ipa
    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USER"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
    )
    yarn(command: "ci:browserstack", project_root: "../")
  end

  desc "increment path version"
  lane :increment do
    increment_version_number(bump_type: "patch")
  end

  desc "build ipa"
  lane :build_ipa do
    match(type: "development", readonly: is_ci)
    gym(scheme: "GaloyApp", export_method: "development", configuration: "Debug", codesigning_identity: "Apple Development: David Borthwick (SU5SVAJAAL)")
  end

end
