# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # update_code_signing_settings(use_automatic_signing: false, path: "GaloyApp.xcodeproj", code_sign_identity:"iPhone Distribution", team_id:"39Q9AL82ZL", bundle_identifier: "match AppStore io.galoy.app")
    increment_build_number(xcodeproj: "GaloyApp.xcodeproj")
    match(type: "appstore", readonly: is_ci)
    gym(scheme: "GaloyApp")
    upload_to_testflight(changelog: "No changelog")
    # update_code_signing_settings(use_automatic_signing: true, path: "GaloyApp.xcodeproj")
  end

end
