# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Build new app version"
  lane :release_build do
    match(type: "appstore", readonly: is_ci)
    gym(scheme: "GaloyApp")
  end

  desc "End to end testing on browserstack"
  lane :browserstack do
    release_build
    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USER"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
    )
    sh("GALOY_TEST_TOKENS=$GALOY_TEST_TOKENS && GALOY_TOKEN_2=$GALOY_TOKEN_2 && yarn test:browserstack:ios")
  end
end
