#@ load("@ytt:data", "data")

#@ def pipeline_image():
#@   return data.values.docker_registry + "/galoy-mobile-pipeline"
#@ end

#@ def release_pipeline_image():
#@   return data.values.docker_registry + "/release-pipeline"
#@ end

#@ def task_image_config():
type: registry-image
source:
  username: #@ data.values.docker_registry_user
  password: #@ data.values.docker_registry_password
  repository: #@ pipeline_image()
#@ end

#@ def release_task_image_config():
type: registry-image
source:
  username: #@ data.values.docker_registry_user
  password: #@ data.values.docker_registry_password
  repository: #@ release_pipeline_image()
#@ end

#@ def cancel_circleci_build_on_abort():
task: cancel
config:
  platform: linux
  image_resource: #@ task_image_config()
  inputs:
  - name: pipeline-tasks
  - name: job-number
  run:
    path: pipeline-tasks/ci/tasks/cancel-circleci-job.sh
  params:
    CIRCLECI_TOKEN: #@ data.values.circleci_token
#@ end

groups:
- name: all
  jobs:
  - test-unit
  - check-code
  - install-deps
  - dev-build-android
  - dev-build-ios
  - e2e-test-android
  - e2e-test-ios
  - prerelease
  - prod-build-android
  - prod-build-ios
  - build-pipeline-image
- name: development
  jobs:
  - test-unit
  - check-code
  - install-deps
  - dev-build-android
  - dev-build-ios
- name: e2e-builds
  jobs:
  - e2e-test-android
  - e2e-test-ios
  - prerelease
  - prod-build-android
  - prod-build-ios
- name: image
  jobs:
  - build-pipeline-image

jobs:
- name: install-deps
  plan:
  - in_parallel:
    - { get: deps, trigger: true }
    - { get: pipeline-tasks }
    - { put: deps-version, params: { bump: patch } }
  - task: install-deps
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: pipeline-tasks
      - name: deps
      - name: deps-version
      outputs:
      - name: bundled-deps
      run:
        path: pipeline-tasks/ci/tasks/install-deps.sh
  - put: bundled-deps
    params:
      file: bundled-deps/bundled-deps-*.tgz

- name: test-unit
  plan:
  - in_parallel:
    - { get: repo, trigger: true }
    - { get: bundled-deps, trigger: true }
    - get: pipeline-tasks
  - task: test-unit
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: bundled-deps
      - name: pipeline-tasks
      - name: repo
      run:
        path: pipeline-tasks/ci/tasks/test-unit.sh

- name: check-code
  plan:
  - in_parallel:
    - { get: repo, trigger: true }
    - { get: bundled-deps, trigger: true }
    - get: pipeline-tasks
  - task: test-unit
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: bundled-deps
      - name: pipeline-tasks
      - name: repo
      run:
        path: pipeline-tasks/ci/tasks/check-code.sh

- name: dev-build-android
  serial: true
  plan:
  - in_parallel:
    - get: repo
      trigger: true
      passed:
      - test-unit
      - check-code
    - get: pipeline-tasks
    - get: build-number-android
  - task: build
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: repo
      - name: pipeline-tasks
      - name: build-number-android
      outputs:
      - name: job-number
      run:
        path: pipeline-tasks/ci/tasks/build-on-circleci.sh
      params:
        PLATFORM: android
        WAIT_FOR_BUILD_MINS: 30
        BUILD_NUMBER_FILE: build-number-android/android
        GIT_REF_FILE: repo/.git/ref
        VERSION_FILE: repo/.git/ref
        GCS_DIRECTORY: dev/android
        CIRCLECI_TOKEN: #@ data.values.circleci_token
    on_abort: #@ cancel_circleci_build_on_abort()

- name: dev-build-ios
  serial: true
  plan:
  - in_parallel:
    - get: repo
      trigger: true
      passed:
      - test-unit
      - check-code
    - get: pipeline-tasks
    - get: build-number-ios
  - task: build
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: repo
      - name: pipeline-tasks
      - name: build-number-ios
      outputs:
      - name: job-number
      run:
        path: pipeline-tasks/ci/tasks/build-on-circleci.sh
      params:
        PLATFORM: ios
        WAIT_FOR_BUILD_MINS: 45
        BUILD_NUMBER_FILE: build-number-ios/ios
        GIT_REF_FILE: repo/.git/ref
        VERSION_FILE: repo/.git/ref
        GCS_DIRECTORY: dev/ios
        CIRCLECI_TOKEN: #@ data.values.circleci_token
    on_abort: #@ cancel_circleci_build_on_abort()

- name: e2e-test-android
  serial: true
  plan:
  - in_parallel:
    - get: built-dev-apk
      trigger: true
    - get: repo
      passed: ["dev-build-android"]
      trigger: true
    - get: bundled-deps
      passed: ["test-unit"]
    - get: pipeline-tasks
  - task: e2e-test
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: repo
      - name: bundled-deps
      - name: built-dev-apk
      - name: pipeline-tasks
      run:
        path: pipeline-tasks/ci/tasks/e2e-test-android.sh
      params:
        BROWSERSTACK_USER: #@ data.values.browserstack_user
        BROWSERSTACK_ACCESS_KEY: #@ data.values.browserstack_access_key
        BROWSERSTACK_ANDROID_BUILD: #@ data.values.browserstack_android_build
        GALOY_TEST_TOKENS: #@ data.values.galoy_test_tokens
        GALOY_TOKEN_2: #@ data.values.galoy_token_2

- name: e2e-test-ios
  serial: true
  plan:
  - in_parallel:
    - get: built-dev-ipa
      trigger: true
    - get: repo
      passed: ["dev-build-ios"]
      trigger: true
    - get: bundled-deps
      passed: ["test-unit"]
    - get: pipeline-tasks
  - task: e2e-test
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: repo
      - name: bundled-deps
      - name: built-dev-ipa
      - name: pipeline-tasks
      run:
        path: pipeline-tasks/ci/tasks/e2e-test-ios.sh
      params:
        BROWSERSTACK_USER: #@ data.values.browserstack_user
        BROWSERSTACK_ACCESS_KEY: #@ data.values.browserstack_access_key
        BROWSERSTACK_IOS_BUILD: #@ data.values.browserstack_ios_build
        GALOY_TEST_TOKENS: #@ data.values.galoy_test_tokens
        GALOY_TOKEN_2: #@ data.values.galoy_token_2

- name: prerelease
  serial: true
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: repo
      passed: ["e2e-test-android", "e2e-test-ios"]
      params:
        fetch_tags: true
    - get: built-dev-ipa
      passed: [ e2e-test-ios ]
    - get: built-dev-apk
      passed: [ e2e-test-android ]
    - get: pipeline-tasks
    - get: testflight-version
  - task: choose-commit-prerelease
    config:
      platform: linux
      image_resource: #@ release_task_image_config()
      inputs:
      - name: repo
      - name: pipeline-tasks
      - name: built-dev-ipa
      - name: built-dev-apk
      outputs:
      - name: repo
      - name: artifacts
      run:
        path: pipeline-tasks/ci/tasks/choose-commit-prerelease.sh
  - task: prep-release
    config:
      platform: linux
      image_resource: #@ release_task_image_config()
      inputs:
      - name: repo
      - name: pipeline-tasks
      - name: testflight-version
      - name: artifacts
      outputs:
      - name: testflight-version
      - name: artifacts
      run:
        path: pipeline-tasks/ci/tasks/prerelease.sh
  - in_parallel:
    - put: gh-prerelease
      params:
        name: artifacts/gh-release-name
        tag: artifacts/gh-release-tag
        body: artifacts/gh-release-notes.md
        commitish: artifacts/commit-id
    - put: testflight-version
      params:
        file: testflight-version/version

- name: prod-build-android
  serial: true
  plan:
  - in_parallel:
    - get: repo
      passed: ["prerelease"]
    - get: build-number-android
    - get: pipeline-tasks
    - get: built-dev-apk
      passed: [ "prerelease" ]
      trigger: true
    - get: testflight-version
      passed: [ "prerelease" ]
  - task: bump-and-commit-build-number
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: pipeline-tasks
      - name: build-number-android
        path: build-number
      - name: testflight-version
        path: version
      outputs:
      - name: build-number-android
        path: build-number
      run:
        path: pipeline-tasks/ci/tasks/bump-and-commit-build-number.sh
      params:
        PLATFORM: android
  - task: build
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: repo
      - name: pipeline-tasks
      - name: build-number-android
      - name: built-dev-apk
      - name: testflight-version
      outputs:
      - name: job-number
      run:
        path: pipeline-tasks/ci/tasks/build-on-circleci.sh
      params:
        PLATFORM: android
        WAIT_FOR_BUILD_MINS: 30
        BUILD_NUMBER_FILE: build-number-android/android
        GIT_REF_FILE: built-dev-apk/url
        GIT_REF_PATTERN: dev/android/galoy-mobile-.+-v(.+)/apk
        VERSION_FILE: testflight-version/version
        GCS_DIRECTORY: prod/android
        CIRCLECI_TOKEN: #@ data.values.circleci_token
    on_abort: #@ cancel_circleci_build_on_abort()
  - put: build-number-android
    params:
      repository: build-number-android
      rebase: true

- name: prod-build-ios
  serial: true
  plan:
  - in_parallel:
    - get: repo
      passed: ["prerelease"]
    - get: pipeline-tasks
    - get: build-number-ios
    - get: built-dev-ipa
      passed: [ "prerelease" ]
      trigger: true
    - get: testflight-version
      passed: [ "prerelease" ]
  - task: bump-and-commit-build-number
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: pipeline-tasks
      - name: build-number-ios
        path: build-number
      - name: testflight-version
        path: version
      outputs:
      - name: build-number-ios
        path: build-number
      run:
        path: pipeline-tasks/ci/tasks/bump-and-commit-build-number.sh
      params:
        PLATFORM: ios
  - task: build
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: repo
      - name: pipeline-tasks
      - name: build-number-ios
      - name: built-dev-ipa
      - name: testflight-version
      outputs:
      - name: job-number
      run:
        path: pipeline-tasks/ci/tasks/build-on-circleci.sh
      params:
        PLATFORM: ios
        WAIT_FOR_BUILD_MINS: 45
        BUILD_NUMBER_FILE: build-number-ios/ios
        GIT_REF_FILE: built-dev-ipa/url
        GIT_REF_PATTERN: dev/ios/galoy-mobile-.+-v(.+)/Blink
        VERSION_FILE: testflight-version/version
        GCS_DIRECTORY: prod/ios
        CIRCLECI_TOKEN: #@ data.values.circleci_token
    on_abort: #@ cancel_circleci_build_on_abort()
  - put: build-number-ios
    params:
      repository: build-number-ios
      rebase: true

- name: build-pipeline-image
  serial: true
  plan:
  - get: pipeline-image-def
    trigger: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: pipeline-image-def
      outputs:
      - name: image
      params:
        CONTEXT: pipeline-image-def/ci/image
      run:
        path: build
  - put: pipeline-image
    params:
      image: image/image.tar

resources:
- name: repo
  type: git
  webhook_token: ((webhook.secret))
  source:
    ignore_paths:
    - "ci/*"
    - ".circleci/*"
    - ".github/*"
    - "docs/*"
    - "README.md"
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

- name: pipeline-tasks
  type: git
  source:
    paths: [ "ci/*" ]
    uri: #@ data.values.git_uri
    branch: #@ data.values.pipeline_git_branch
    private_key: #@ data.values.github_private_key

- name: deps
  type: git
  webhook_token: ((webhook.secret))
  source:
    paths: [ yarn.lock ]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

- name: bundled-deps
  type: gcs-resource
  source:
    bucket: #@ data.values.artifacts_bucket_name
    json_key: #@ data.values.staging_inception_creds
    regexp: galoy-mobile-artifacts/deps/bundled-deps-v(.*)-.*.tgz

- name: built-dev-apk
  type: gcs-resource
  source:
    bucket: #@ data.values.build_artifacts_bucket_name
    json_key: #@ data.values.build_artifacts_bucket_creds
    regexp: galoy-mobile/dev/android/galoy-mobile-(.+)-v.+/apk/release/app-universal-release.apk

- name: built-dev-ipa
  type: gcs-resource
  source:
    bucket: #@ data.values.build_artifacts_bucket_name
    json_key: #@ data.values.build_artifacts_bucket_creds
    regexp: galoy-mobile/dev/ios/galoy-mobile-(.+)-v.+/Blink.ipa

- name: deps-version
  type: semver
  source:
    initial_version: 0.1.0
    driver: gcs
    bucket: #@ data.values.artifacts_bucket_name
    key: galoy-mobile-artifacts/versions/deps
    json_key: #@ data.values.staging_inception_creds

- name: pipeline-image
  type: registry-image
  source:
    tag: latest
    username: #@ data.values.docker_registry_user
    password: #@ data.values.docker_registry_password
    repository: #@ pipeline_image()

- name: pipeline-image-def
  type: git
  source:
    paths: [ci/image/Dockerfile]
    uri: #@ data.values.git_uri
    branch: #@ data.values.pipeline_git_branch
    private_key: #@ data.values.github_private_key

- name: daily
  type: time
  source:
    day_of_week: 1-6
    start: 6:00 AM
    stop: 6:00 AM
    location: UTC

- name: gh-prerelease
  type: github-release
  source:
    owner: #@ data.values.gh_org
    repository: #@ data.values.gh_repository
    access_token: #@ data.values.github_api_token
    release: false
    pre_release: true

- name: testflight-version
  type: semver
  source:
    initial_version: 0.0.1
    driver: git
    file: testflight-version
    git_user: galoybot <bot@galoy.io>
    commit_message: "release(testflight): v%version%"
    uri: #@ data.values.git_mobile_deployments_uri
    branch: #@ data.values.git_version_branch
    private_key: #@ data.values.github_private_key

- name: build-number-android
  type: git
  source:
    paths: [ "android", "android-builds" ]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_build_number_branch
    private_key: #@ data.values.github_private_key

- name: build-number-ios
  type: git
  source:
    paths: [ "ios", "ios-builds" ]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_build_number_branch
    private_key: #@ data.values.github_private_key

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource
