# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :build do
    increment_version_code(gradle_file_path: "app/build.gradle")
    gradle(
      task: "clean assemble",
      build_type: "Release",
      print_command: false,
      flags: "--no-daemon --max-workers=8 --stacktrace --info"
    )
    # gradle(task: "clean assembleRelease", print_command: false)

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :beta do
    build
    # crashlytics
    upload_to_play_store(
      track: "internal",
      skip_upload_changelogs: true,
      skip_upload_images: true,
    )
  end

#  desc "Promote Internal to Alpha"
#  lane :promote_internal_to_alpha do
#    upload_to_play_store(
#      track: 'internal',
#      track_promote_to: 'alpha',
#      version_code: 145,
#      skip_upload_changelogs: true,
#      skip_upload_images: true
#      )
#  end

end
