# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build Releasable APK"
  lane :build do
    android_set_version_name(version_name: ENV["PUBLIC_VERSION"])
    gradle(task: 'clean')
    gradle(
      task: "assemble",
      build_type: "Release",
      flags: "--no-daemon --stacktrace --info",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :play_store_upload do
    upload_to_play_store(
      apk: "./app-universal-release.apk",
      track: "internal",
      skip_upload_changelogs: true,
      skip_upload_images: true,
    )
  end

  desc "Deploy a new version to Huawei App Gallery"
  lane :huawei_store_upload do
    huawei_appgallery_connect(
      client_id: ENV["HUAWEI_CLIENT_ID"],
      client_secret: ENV["HUAWEI_CLIENT_SECRET"],
      app_id: ENV["HUAWEI_APP_ID"],
      apk_path: "./app-universal-release.apk",
      phase_wise_release: true,
      phase_release_percent: "1",
      phase_release_description: "Phased Release",
      submit_for_review: false
    )
  end

  desc "Build for end to end testing"
  lane :build_e2e do
    gradle(
      task: "clean assemble",
      build_type: "Debug",
      print_command: false,
      flags: "--no-daemon --max-workers=8 --stacktrace --info",
    )
  end

  desc "End to end testing on browserstack"
  lane :browserstack do
    build_e2e
    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USER"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: ENV["GRADLE_APK_OUTPUT_PATH"]
    )
    sh("GALOY_TEST_TOKENS=$GALOY_TEST_TOKENS && GALOY_TOKEN_2=$GALOY_TOKEN_2 && yarn test:browserstack:android")
  end


  desc "Submit a new build Deploy gate"
  lane :release_dg do 
    build_apk

    deploygate(
      api_token: ENV["deploygate_token"],
      user: ENV["deploygate_user"],
      message: "Build #{lane_context[SharedValues::BUILD_NUMBER]}",
    )
  end 

  desc "Create Release APK"
  lane :build_apk do
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV["store_file"],
        "android.injected.signing.store.password" => ENV["store_password"],
        "android.injected.signing.key.alias" => ENV["key_alias"],
        "android.injected.signing.key.password" => ENV["key_password"],
      }
    )
  end
end