# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a new version of the app"
  lane :build do
    increment_version_code(gradle_file_path: "app/build.gradle")
    android_set_version_name(version_name: ENV["CIRCLE_TAG"])
    gradle(task: 'clean')
    gradle(
      task: "assemble",
      build_type: "Release",
      flags: "--no-daemon --stacktrace --info",
    )
  end

  desc "Create a new releasable apk"
  lane :release_build do
    gradle(task: 'clean')
    gradle(
      task: "assemble",
      build_type: "Release",
      flags: "--no-daemon --stacktrace --info",
    )
  end

  desc "End to end testing on browserstack"
  lane :browserstack do
    release_build
    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USER"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: ENV["GRADLE_APK_OUTPUT_PATH"]
    )
    sh("GALOY_TEST_TOKENS=$GALOY_TEST_TOKENS && GALOY_TOKEN_2=$GALOY_TOKEN_2 && yarn test:browserstack:android")
  end
end
