name: "Check code"
on:
  pull_request:
    branches: [main, usd-integration]
jobs:
  check-code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - name: Run check code
        run: yarn check-code
