name: E2E against Local

on: [push]

jobs:
  tilt-ci-android:
    name: Tilt CI Android
    runs-on: ["self-hosted", "Linux", "X64"]

    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Tilt CI
        run: |
          for i in {1..5}; do
            echo "Tilt CI attempt $i"
            nix develop -c sh -c 'cd dev && tilt ci' && exit 0 || sleep 15
          done
          exit 1
      - name: Destroy backend
        if: always()
        continue-on-error: true
        run: |
          nix develop -c sh -c 'cd dev && tilt down' || true
          docker rm -f $(docker ps -aq)

  tilt-ci-ios:
    name: Tilt CI MacOS
    runs-on: ["self-hosted", "MacOS", "ARM64"]

    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Tilt CI
        run: |
          for i in {1..5}; do
            echo "Tilt CI attempt $i"
            nix develop -c sh -c 'cd dev && tilt ci' && exit 0 || sleep 15
          done
          exit 1
      - name: Destroy backend
        if: always()
        continue-on-error: true
        run: |
          nix develop -c sh -c 'cd dev && tilt down' || true
          docker rm -f $(docker ps -aq)
