name: E2E

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: E2E Tests
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      # In case this is run on a runner without nix
      # - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: nicknovitski/nix-develop@v1

      # Caching
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            ios/Pods
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock', '**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      # Installations
      - name: Install Node Modules and Pods
        run: yarn install
        env:
          LANG: en_US.UTF-8

      # Metro
      - name: Start Metro
        run: |
          yarn start &
          echo "METRO_PID=$!" >> $GITHUB_ENV

      # Builds
      - run: yarn e2e:build ios.sim.debug
      - run: yarn e2e:build android.emu.debug

      # Start Tilt
      - name: Tilt CI
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          retry_wait_seconds: 15
          max_attempts: 5
          command: cd dev && tilt ci

      # Tests on iOS Simulator
      - name: Run Detox Tests on iOS Simulator
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: |
            rm -rf ios-recordings || true
            yarn e2e:test ios.sim.debug -d --take-screenshots all --record-videos all --record-logs all --artifacts-location ios-recordings

      - run: killall Simulator
        if: always()
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-recordings
          path: ios-recordings

      # Tests on Android Emulator
      - name: Start Android Emulator
        run: |
          make emulator &
          adb wait-for-device

      - name: Run Detox Tests on Android Emulator
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: |
            rm -rf android-recordings || true
            yarn e2e:test android.emu.debug -d --take-screenshots all --record-videos all --record-logs all --artifacts-location android-recordings

      - name: Kill Android Emulator
        if: always()
        continue-on-error: true
        run: adb emu kill

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-recordings
          path: android-recordings

      # Cleanup
      - name: Terminate Metro
        if: always()
        continue-on-error: true
        run: kill $METRO_PID

      - name: Destroy backend
        if: always()
        continue-on-error: true
        run: |
          cd dev && tilt down || true
          docker volume prune -af || true
          docker rm -f $(docker ps -aq)
