name: Test Android in PR
on: 
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install
        run: |
          yarn install
          cd android
          bundle config set deployment 'true'
          bundle check || bundle install
          yarn android:prepareAssets
      - name: Build & Test on Browserstack
        run: |
          set -o pipefail
          echo $RELEASE_KEYSTORE | base64 -d > android/app/release.keystore
          cd android && bundle exec fastlane browserstack | tee browserstack_output.log
          error_code=$?
          SESSION_ID=$(cat browserstack_output.log | grep sessionId | head -n1 | sed -n "s/^.*'\(.*\)'.*$/\1/ p")
          echo "Session ID"
          echo $SESSION_ID
          VIDEO_URL=$(curl -s -u "$BROWSERSTACK_USER:$BROWSERSTACK_ACCESS_KEY" -X GET "https://api-cloud.browserstack.com/app-automate/sessions/$SESSION_ID.json" | jq -r '.automation_session.video_url')
          echo "Video URL"
          echo $VIDEO_URL
          exit $error_code
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          GALOY_TEST_TOKENS: ${{ secrets.GALOY_TEST_TOKENS }}
          GALOY_TOKEN_2: ${{ secrets.GALOY_TOKEN_2 }}
