name: "Test"
on:
  pull_request:
    branches: [main]
jobs:
  check-code:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - name: Run test
        run: yarn test
